#version: '3'
#
#services:
#  app:
#    build: ./
#    container_name: 'JavaEmailContainer'
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_RABBITMQ_HOST: rabbitmq
#      SPRING_RABBITMQ_PORT: 5672
#      SPRING_PROFILES_ACTIVE: production
#    depends_on:
#      - rabbitmq
#
#  rabbitmq:
#    image: "rabbitmq:3-management"
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    environment:
#      RABBITMQ_DEFAULT_USER: rmuser
#      RABBITMQ_DEFAULT_PASS: rmpassword

version: '3.8'

services:
  app:
    build:
      context: ./
    container_name: 'JavaEmailContainer'
    ports:
      - "8080:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_PROFILES_ACTIVE: production
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rmuser
      RABBITMQ_DEFAULT_PASS: rmpassword
